### ISSUE TITLE
Compiling solid with Numpy 1.26.0 fails

### ISSUE THREAD

**Issue by florianhuisman** [aresys-srl/sar-calibration-tool#6]
Recompiling the external tool called solid, [as described in the documentation](https://github.com/aresys-srl/sar-calibration-tool/blob/06e67061217b6c1747c1c79b46129c113e9c1374/docs/install.rst#support-tools-solid) using `f2py`, with Numpy 1.26.0 results in the following error:

```
Traceback (most recent call last):
  File "/opt/s1mpc/bin/f2py", line 10, in <module>
    sys.exit(main())
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/f2py2e.py", line 732, in main
    run_compile()
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/f2py2e.py", line 705, in run_compile
    builder.compile()
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/_backends/_distutils.py", line 71, in compile
    setup(ext_modules=[ext])
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/distutils/command/build.py", line 62, in run
    old_build.run(self)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/s1mpc/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
    self.build_extension_sources(ext)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/distutils/command/build_src.py", line 321, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
    f2py2e.run_main(f2py_options + ['--lower',
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/f2py2e.py", line 462, in run_main
    postlist = callcrackfortran(files, options)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/f2py2e.py", line 363, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/crackfortran.py", line 3355, in crackfortran
    readfortrancode(files, crackline)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/crackfortran.py", line 552, in readfortrancode
    dowithline(finalline)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/crackfortran.py", line 858, in crackline
    analyzeline(m, pat[1], line)
  File "/opt/s1mpc/lib/python3.9/site-packages/numpy/f2py/crackfortran.py", line 1452, in analyzeline
    vtype = vars[v].get('typespec')
KeyError: 'dhi'
```

**Comment by mcvittal** [comment]
I am getting the same error on my machine. @rpiantanida any ideas?
